package com.pefish.joy.greendaotest.daos;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pefish.joy.greendaotest.entities.ExtraData;
import com.pefish.joy.greendaotest.entities.Suggestion;
import com.pefish.joy.greendaotest.entities.TestHttpApi;
import com.pefish.joy.greendaotest.entities.User;

import com.pefish.joy.greendaotest.daos.ExtraDataDao;
import com.pefish.joy.greendaotest.daos.SuggestionDao;
import com.pefish.joy.greendaotest.daos.TestHttpApiDao;
import com.pefish.joy.greendaotest.daos.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig extraDataDaoConfig;
    private final DaoConfig suggestionDaoConfig;
    private final DaoConfig testHttpApiDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ExtraDataDao extraDataDao;
    private final SuggestionDao suggestionDao;
    private final TestHttpApiDao testHttpApiDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        extraDataDaoConfig = daoConfigMap.get(ExtraDataDao.class).clone();
        extraDataDaoConfig.initIdentityScope(type);

        suggestionDaoConfig = daoConfigMap.get(SuggestionDao.class).clone();
        suggestionDaoConfig.initIdentityScope(type);

        testHttpApiDaoConfig = daoConfigMap.get(TestHttpApiDao.class).clone();
        testHttpApiDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        extraDataDao = new ExtraDataDao(extraDataDaoConfig, this);
        suggestionDao = new SuggestionDao(suggestionDaoConfig, this);
        testHttpApiDao = new TestHttpApiDao(testHttpApiDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(ExtraData.class, extraDataDao);
        registerDao(Suggestion.class, suggestionDao);
        registerDao(TestHttpApi.class, testHttpApiDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        extraDataDaoConfig.clearIdentityScope();
        suggestionDaoConfig.clearIdentityScope();
        testHttpApiDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ExtraDataDao getExtraDataDao() {
        return extraDataDao;
    }

    public SuggestionDao getSuggestionDao() {
        return suggestionDao;
    }

    public TestHttpApiDao getTestHttpApiDao() {
        return testHttpApiDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
